# Generated by Django 4.1 on 2022-09-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='author',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='home.author'),
            preserve_default=False,
        ),
    ]
