# Generated by Django 4.1 on 2022-09-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_house_author_alter_rating_rating_house_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='author',
        ),
    ]
