# Generated by Django 4.1 on 2022-09-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_house_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.author'),
            preserve_default=False,
        ),
    ]
