# Generated by Django 4.1 on 2022-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_house_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='author',
        ),
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ManyToManyField(to='home.author'),
        ),
    ]
